### ISSUE TITLE
Text is not centered

### ISSUE THREAD

**Issue by islovingness** [ieskudero/three-dxf-viewer#11]
dxf files in cad, text can identify anchor points in the middle and lower, middle and upper. But in three-dxf-viewer it seems to always be the bottom left;

dxf zip is attached.

thank you!
[Uploading test.zip…]()

**Comment by islovingness** [comment]
> dxf files in cad, text can identify anchor points in the middle and lower, middle and upper. But in three-dxf-viewer it seems to always be the bottom left;
> 
> dxf zip is attached.
> 
> thank you! Uploading test.zip…

[test.zip](https://github.com/user-attachments/files/15799343/test.zip)

**Comment by islovingness** [comment]
The cause of the problem should be
textEntity._getPosAndRotation does not use entity.hAlign and entity.vAlign, right?

**Comment by ieskudero** [comment]
Could be, I will try to check it.

**Comment by aceway** [comment]
Maybe the same problum that I encountered, this file's scene looks like this in my fixed local version: 
![1](https://github.com/ieskudero/three-dxf-viewer/assets/1401796/26a893c5-5ab5-4b2f-9643-73c74984a28d)

**Comment by ieskudero** [comment]
Looks like you were right! The text needed vertical and horizontal alignment, as you suggested. I created a method to align the text, `_alignText`, but I would need a few more examples to fix all the possible alignments. I'll close this issue until more examples arrives with specific alignments. Thanks for the help!
