### ISSUE TITLE
Error creating DXFViewer instance

### ISSUE THREAD

**Issue by andrelzsousa** [ieskudero/three-dxf-viewer#14]
Im using react and when i load a dxf file for testing i get the following error:

![image](https://github.com/ieskudero/three-dxf-viewer/assets/107645540/664e4865-60fb-494b-a1b6-5a1d299c790d)

Im not sure whats happening, cause i did correctly ran `npm install three-dxf-viewer` and it is located on my package.json file.
How can i solve this?

**Comment by ieskudero** [comment]
How are you loading the DXFViewer class? I can't see why it could break loading the class unless I see the code. However, I have made a minimun application with react & vite, based on the react example, that shows how to use it
[dxftest.zip](https://github.com/user-attachments/files/15892127/dxftest.zip)

Hopes it help. Let me know if this runs or not.

**Comment by andrelzsousa** [comment]
Thanks for the response.
So, i downloaded and tried to run the project you sent. It seems that the DXFViewer class error is gone and there isnt any TS error either. But a new error has apperead when i load a dxf file on the input:
![image](https://github.com/ieskudero/three-dxf-viewer/assets/107645540/f6e7598a-8ebd-47bd-b122-51f490e90b38)
Have you ever faced this one? Do you know how to solve it?

Thanks in advance!!!

**Comment by ieskudero** [comment]
Can you pass me the dxf file that gives you that error? I think it is easily fixable if I check for undefined x,y or z values, but I don't know why there are undefined values in that entity. I would need the dxf file to verify it.
