### ISSUE TITLE
issue using in typescript/webpack project

### ISSUE THREAD

**Issue by berry4u** [ieskudero/three-dxf-viewer#3]
i've got the error: Cannot read properties of undefined (reading '__esModule') when included in a typescript project with webpack and using require, since @types definition is not available . This is what I get:
![image](https://user-images.githubusercontent.com/33978204/221160449-e98965dc-83ac-43ae-8284-6b6cb99f769e.png)

**Comment by ieskudero** [comment]
Sorry @berry4u but I am having trouble finding the error since I have never used Typescript. Can you clarify it a little bit more?
